name = "raven"
main = "src/index.ts"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2025-06-15"

[observability]
enabled = true

[vars]
GDRIVE_API_CLIENT_ID = "666634454375-hlqgdhlqkjagckg1cad0e0tb516mjmpn.apps.googleusercontent.com"
GDRIVE_FOLDER_ID = "1RiLSVxvn0unXyCNP5GMRKgWYB1CW855B"
BACKUP_EMAIL = "raven-backup@z1k.dev"
