name = "raven"
main = "src/index.ts"
compatibility_date = "2025-06-15"

[observability]
enabled = true

[vars]
NEXTCLOUD_URL = "https://nextcloud.highgarden.blahgeek.com"
NEXTCLOUD_USERNAME = "blahgeek-raven"
NEXTCLOUD_MAILDIR_PATH = "Maildir"
BACKUP_EMAIL = "raven-backup@z1k.dev"
